### ISSUE TITLE
Difficulty accessing pre-trained models and test cases

### ISSUE THREAD

**Issue by lukegib** [tangkk/pyace#1]
Hi Junqi,

I am trying to access the pre-trained models you have linked in the project README but am having difficulty. It is re-directing to a website that is entirely in Chinese (looks to be a betting website too?).

Would you be able to host the files in a different location?

**Comment by tangkk** [comment]
Hi Luke,

The link seems to be dead for some reason. I'll try to search for my local
storage and look for those models again. Sorry about that. I'll let you
know.

Junqi

Luke Gibbons <notifications@github.com> 于2020年12月17日周四 下午8:36写道：

**Comment by tangkk** [comment]
OK, I found the models and uploaded them to dropbox, please check out the
github page again.

Luke Gibbons <notifications@github.com> 于2020年12月17日周四 下午8:36写道：

**Comment by lukegib** [comment]
Thanks, Junqi!
